name: Using composite custom actions with Input and Output

on: push

jobs:
  demo:
    runs-on: ubuntu-latest
    steps: 
      - name: get code
        uses: actions/checkout@v4
      - name: Using action
        id: action-step
        uses: ./.github/customs-actions/input-output-composite-actions
        with:
          person-name: 'Amogh'

      - name: Showing output
        run: |
            echo "${{ steps.action-step.outputs.greeting }}"